export const en = {
  Common_done: 'Done',
  Common_btc_address: 'BTC Address',
  Common_copy: 'Copy',
  Common_share: 'Share',
  Common_amount: 'Amount',
  Common_to: 'To',
  Common_save: 'Save',
  Common_password: 'Password',
  Common_search_placeholder: 'Search...',
  Common_receive: 'Receive',
  Common_send: 'Send',
  Common_buy: 'Buy',
  Common_next: 'Next',
  Common_success: 'Success!',
  Common_error: 'Something Went Wrong',
  Common_try_again: 'Try Again',
  Common_balance: 'Balance',
  Common_unlock: 'Unlock',
  Wallet_name: 'TrustMachines',
  Start_screen_title: 'Wallet Value Proposition Sentence',
  Generate_new_wallet_button_text: 'Generate new wallet',
  Import_wallet_button_text: 'Import wallet',
  Biometrics_screen_title: 'Protect Your Wallet',
  Biometrics_screen_subtitle:
    'Adding a biometric security will ensure that you are the only one that can access your wallet.',
  Biometrics_switch_text_first_line: 'Biometric Authentication',
  Biometrics_switch_text_second_line: 'Use FaceID or TouchID',
  Save_recovery_phrase_screen_title: 'Secret Recovery Phrase',
  Save_recovery_phrase_screen_subtitle:
    'This is the only way you will be able to recover your account. Please store itsomewhere safe!',
  Save_recovery_phrase_button_text: 'Okay, I have it saved',
  Copy_to_clipboard: 'Copy to clipboard',
  Create_wallet_success_text: 'Enjoy your Trust Machines Wallet.To the Moon, Alice! To the Moon!',
  Create_wallet_success_switch_text_first_line: 'I agree to the',
  Create_wallet_success_switch_text_second_line: 'Terms of Service',
  Create_wallet_success_button_text: 'Get Started!',
  Home_last_updated_label: 'Last Updated',
  Home_your_transactions: 'Your Transactions',
  Home_view_all: 'View all',
  Header_title_exchange: 'Swap Assets',
  Exchange_screen_pay_label: 'You Pay',
  Exchange_screen_receive_label: 'You Receive',
  Exchange_screen_button_text: 'Swap',
  Exchange_screen_modal_title: 'Select Token',
  Qr_flow_modal_title: 'Send/Receive via QR',
  Qr_flow_present_qr_title: 'Your QR Code',
  Qr_flow_present_qr_button_text: 'Scan QR',
  Qr_flow_swapping_assets_label: 'Send by Swapping Tokens',
  Qr_flow_transaction_success_title: 'Transaction Successfully Sent!',
  Send_screen_select_contact_label: 'Select Contact',
  Send_screen_add_contact_label: 'Add Contact',
  Header_title_collectibles: 'Collectibles',
  Defi_browser_launch_label: 'Launch DeFi apps here',
  Defi_browser_search_placeholder: 'Search or enter URL...',
  Settings_label_profile: 'Profile',
  Settings_label_security: 'Security',
  Settings_label_notifications: 'Notifications',
  Settings_label_others: 'Others',
  Header_title_settings: 'Settings',
  Settings_screen_recovery_phrase: 'Recovery phrase',
  Settings_screen_app_lock: 'App lock',
  Settings_screen_notifications_settings: 'Notification settings',
  Settings_screen_contact_us: 'Contact us',
  Settings_screen_sign_out: 'Sign out',
  Buy_crypto_modal_title: 'Buy Crypto',
  Buy_crypto_your_address: 'Your Address',
  Buy_crypto_copy_address: 'Copy Address',
  Buy_crypto_moon_pay_button_text: 'Buy with MoonPay',
  Buy_crypto_binance_button_text: 'Transfer from Binance',
  Buy_crypto_ramp_network_button_text: 'Use Ramp Network',
  Wallet_login_screen_title: 'Secret Recovery Phrase',
  Wallet_login_screen_subtitle:
    'Please give us your secret recovery phase so we can restore your wallet',
  Accept_TOS_switch_text_first_line: 'I agree to the',
  Accept_TOS_switch_text_second_line: 'Terms of Service',
  Accept_TOS_button_text: 'Terms of Service',
  Accept_TOS_title: 'Accept TOS',
  Accept_TOS_subtitle: 'Explainer text',
  Set_password_title: 'Add Password',
  Set_password_subtitle: 'Explainer Text',
  Set_password_confirm_password: 'Confirm Password',
  Set_label_title: 'Name your wallet',
  Set_label_subtitle: 'Explainer Text',
  Set_label_placeholder: 'Wallet Label',
  Unlock_wallet_title: 'Unlock Wallet',
  Unlock_wallet_subtitle: 'Explainer Text',
  Wallet_selector_modal_title: 'Select a wallet to use',
  Wallet_selector_add_new_button_text: 'Add New',
  Wallet_selector_use_selected_button_text: 'Use Selected',
  Add_new_wallet_screen_title: 'Add a new wallet',
  Add_new_wallet_generate_button_text: 'Generate new wallet',
  Add_new_wallet_import_button_text: 'Import wallet',
  Header_title_transaction_details: 'Transaction Details',
};
