export default {
  Wallet_name: 'TrustMachines',
  Start_screen_title: 'Wallet Value Proposition Sentence',
  Create_new_wallet_button_text: 'Create new wallet',
  User_has_wallet_button_text: 'I already have a wallet',
  Biometrics_screen_title: 'Protect Your Wallet',
  Biometrics_screen_subtitle:
    'Adding a biometric security will ensure that you are the only one that can access your wallet.',
  Biometrics_switch_text_first_line: 'Biometric Authentication',
  Biometrics_switch_text_second_line: 'Use FaceID or TouchID',
  Common_next: 'Next',
  Save_recovery_phrase_screen_title: 'Secret Recovery Phrase',
  Save_recovery_phrase_screen_subtitle:
    'This is the only way you will be able to recover your account. Please store itsomewhere safe!',
  Save_recovery_phrase_button_text: 'Okay, I have it saved',
  Copy_to_clipboard: 'Copy to clipboard',
  Common_success: 'Success!',
  Create_wallet_success_text:
    'Enjoy your Trust Machines Wallet.To the Moon, Alice! To the Moon!',
  Create_wallet_success_switch_text_first_line: 'I agree to the',
  Create_wallet_success_switch_text_second_line: 'Terms of Service',
  Create_wallet_success_button_text: 'Get Started!',
  Common_balance: 'Balance',
  Home_last_updated_label: 'Last Updated',
  Common_receive: 'Receive',
  Common_send: 'Send',
  Common_buy: 'Buy',
  Home_your_transactions: 'Your Transactions',
  Home_view_all: 'View all',
  Header_title_exchange: 'Swap Assets',
  Exchange_screen_pay_label: 'You Pay',
  Exchange_screen_receive_label: 'You Receive',
  Exchange_screen_button_text: 'Swap',
  Exchange_screen_modal_title: 'Select Token',
  Qr_flow_modal_title: 'Send/Receive via QR',
  Qr_flow_present_qr_title: 'Your QR Code',
  Qr_flow_present_qr_button_text: 'Scan QR',
  Qr_flow_swapping_assets_label: 'Send by Swapping Tokens',
  Qr_flow_transaction_success_title: 'Transaction Successfully Sent!',
  Common_done: 'Done',
  Common_btc_address: 'BTC Address',
  Common_copy: 'Copy',
  Common_share: 'Share',
  Common_amount: 'Amount',
  Common_to: 'To',
  Common_search_placeholder: 'Search...',
  Send_screen_select_contact_label: 'Select Contact',
  Send_screen_add_contact_label: 'Add Contact',
  Header_title_collectibles: 'Collectibles',
  Defi_browser_launch_label: 'Launch DeFi apps here',
  Defi_browser_search_placeholder: 'Search or enter URL...',
  Settings_label_profile: 'Profile',
  Settings_label_security: 'Security',
  Settings_label_notifications: 'Notifications',
  Settings_label_others: 'Others',
  Header_title_settings: 'Settings',
  Settings_screen_recovery_phrase: 'Recovery phrase',
  Settings_screen_app_lock: 'App lock',
  Settings_screen_notifications_settings: 'Notification settings',
  Settings_screen_contact_us: 'Contact us',
  Settings_screen_sign_out: 'Sign out',
  Buy_crypto_modal_title: 'Buy Crypto',
  Buy_crypto_your_address: 'Your Address',
  Buy_crypto_copy_address: 'Copy Address',
  Buy_crypto_moon_pay_button_text: 'Buy with MoonPay',
  Buy_crypto_binance_button_text: 'Transfer from Binance',
  Buy_crypto_ramp_network_button_text: 'Use Ramp Network',
  Wallet_login_screen_title: 'Secret Recovery Phrase',
  Wallet_login_screen_subtitle:
    'Please give us your secret recovery phase so we can restore your wallet',
}
